services:
  server:
    image: docker.gitea.com/gitea:1.25.3
    restart: always
    container_name: gitea
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${POSTGRES_PW}
    ports:
      - 3000:3000
      - 2222:2222
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:14
    restart: always
    container_name: gitea_postgress
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
networks: {}